<?php

$ezbbc_config = array (
  'install' => 1486666983,
  'status' => 1,
  'style_folder' => 'Round-css3',
  'smilies_set' => 'ezbbc_smilies',
  'h_id' => 'no_h_id',
  'video' => 'no_video',
  'img_upload' => 'no_img_upload',
  'img_folder' => 'img',
  'max_img_width' => '600',
  'max_img_size' => 500,
  'img_list' => 'no_img_list',
  'img_limit' => 10,
  'img_limit_mod' => 30,
  'doc_upload' => 'no_doc_upload',
  'doc_folder' => 'doc',
  'max_doc_size' => 450,
  'allowed_ext' => 'doc,xls,pdf',
  'doc_list' => 'no_doc_list',
  'doc_limit' => 10,
  'doc_limit_mod' => 30,
  'b' => 'b',
  'u' => 'u',
  'i' => 'i',
  's' => 's',
  'del' => 'del',
  'ins' => 'ins',
  'em' => 'em',
  'color' => 'color',
  'heading' => 'heading',
  'url' => 'url',
  'email' => 'email',
  'img' => 'img',
  'quote' => 'quote',
  'code' => 'code',
  'ulist' => 'ulist',
  'olist' => 'olist',
  'alist' => 'alist',
  'smiliesb' => 'smiliesb',
  'help' => 'help',
  'post_toolbar' => 'post_toolbar',
  'quickpost_toolbar' => 'quickpost_toolbar',
  'signature_toolbar' => 'signature_toolbar',
  'smiliesbar_position' => 'sb_over_tb',
  'bars_position' => 'bars_left',
  'syntax_highlight' => 'no_syntax_highlight',
);

?>